import mongoose from "mongoose";
import dotenv from "dotenv";
import { Menu } from "../models/menu.model.js";

dotenv.config();

const menuItems = [
  // STUFF PARATHA
  {
    name: "Plain Paratha",
    price: 40,
    category: "Stuff Paratha",
    description: "Traditional plain paratha made fresh",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764874085/resize-17648740611236089021plainparatha_r59a4u.png",
    isAvailable: true,
  },
  {
    name: "Jeera Masala Paratha",
    price: 50,
    category: "Stuff Paratha",
    description: "Paratha with cumin and spices",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764874536/jeera_masala_paratha_g6es2j.png",
    isAvailable: true,
  },
  {
    name: "Sweet Paratha",
    price: 50,
    category: "Stuff Paratha",
    description: "Sweet paratha with jaggery",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764880665/sweet_paratha_an9bxl.png",
    isAvailable: true,
  },
  {
    name: "Aloo Paratha",
    price: 100,
    category: "Stuff Paratha",
    description: "Paratha stuffed with spiced potatoes",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764880990/aloo_paratha_fvoffa.png",
    isAvailable: true,
  },
  {
    name: "Methi Paratha",
    price: 100,
    category: "Stuff Paratha",
    description: "Paratha with fresh fenugreek leaves",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881085/methi_paratha_jfhj1t.png",
    isAvailable: true,
  },
  {
    name: "Onion Paratha",
    price: 100,
    category: "Stuff Paratha",
    description: "Paratha stuffed with onions",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881112/onion_paratha_rr7wkb.png",
    isAvailable: true,
  },
  {
    name: "Gobi Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Paratha stuffed with cauliflower",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881121/gobi_paratha_y50otq.png",
    isAvailable: true,
  },
  {
    name: "Mix Veg Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Mixed vegetable stuffed paratha",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881130/mix_veg_paratha_wfzevu.png",
    isAvailable: true,
  },
  {
    name: "Moong Dal Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Paratha stuffed with moong dal",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881232/moong_dal_paratha_t1h02l.png",
    isAvailable: true,
  },
  {
    name: "Garlic Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Paratha with garlic",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881241/garlic_paratha_uumh10.png",
    isAvailable: true,
  },
  {
    name: "Green Peas Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Paratha with green peas",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881249/green_peas_paratha_ihs6yl.png",
    isAvailable: true,
  },
  {
    name: "Sattu Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Paratha with sattu filling",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881258/sattu_paratha_cmspxw.png",
    isAvailable: true,
  },
  {
    name: "Namkeen Sev Paratha",
    price: 110,
    category: "Stuff Paratha",
    description: "Paratha with namkeen sev",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881267/namkeen_sev_paratha_ef8b5a.png",
    isAvailable: true,
  },
  {
    name: "Paneer Paratha",
    price: 120,
    category: "Stuff Paratha",
    description: "Paratha stuffed with paneer",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881273/paneer_paratha_btdhjh.png",
    isAvailable: true,
  },
  {
    name: "Cheese Paratha",
    price: 150,
    category: "Stuff Paratha",
    description: "Paratha with melted cheese",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881281/cheese_paratha_g1p4xc.png",
    isAvailable: true,
  },

  // PREMIUM PARATHA
  {
    name: "Aloo Onion Paratha",
    price: 110,
    category: "Premium Paratha",
    description: "Premium potato and onion paratha",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881579/aloo_onion_paratha_aytrjv.png",
    isAvailable: true,
  },
  {
    name: "Aloo Methi Mix",
    price: 110,
    category: "Premium Paratha",
    description: "Premium mix of potato and fenugreek",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881609/aloo_methi_paratha_adapwj.png",
    isAvailable: true,
  },
  {
    name: "Aloo Onion Methi Mix",
    price: 110,
    category: "Premium Paratha",
    description: "Premium triple mix - potato, onion, fenugreek",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881628/aloo_onion_methi_mix_e0zth5.png",
    isAvailable: true,
  },
  {
    name: "Aloo Onion Garlic Mix",
    price: 120,
    category: "Premium Paratha",
    description: "Premium potato, onion and garlic mix",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881773/aloo_onion_garlic_mix_qyfxsu.png",
    isAvailable: true,
  },
  {
    name: "Mix Veg Garlic Mix",
    price: 120,
    category: "Premium Paratha",
    description: "Premium mixed vegetables with garlic",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881835/mix_veg_garlic_mix_mv5e9q.png",
    isAvailable: true,
  },
  {
    name: "Aloo Methi Garlic Mix",
    price: 120,
    category: "Premium Paratha",
    description: "Premium potato, fenugreek and garlic",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881849/aloo_methi_garlic_mix_vdg9cp.png",
    isAvailable: true,
  },
  {
    name: "Namkeen Sev Onion",
    price: 120,
    category: "Premium Paratha",
    description: "Premium namkeen sev with onion",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881862/namkin_sev_onion_ci3i9e.png",
    isAvailable: true,
  },
  {
    name: "Aloo Gobi Onion Mix",
    price: 120,
    category: "Premium Paratha",
    description: "Premium potato, cauliflower and onion",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881869/aloo_gobi_onion_mix_ciaeiv.png",
    isAvailable: true,
  },
  {
    name: "Aloo Paneer Mix",
    price: 130,
    category: "Premium Paratha",
    description: "Premium potato and cottage cheese",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881877/aloo_paneer_mix_qgkefj.png",
    isAvailable: true,
  },
  {
    name: "Cheese Chilly",
    price: 130,
    category: "Premium Paratha",
    description: "Premium cheese and green chilli",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881887/cheese_chilly_dy33pn.png",
    isAvailable: true,
  },
  {
    name: "Cheese Paneer Mix",
    price: 150,
    category: "Premium Paratha",
    description: "Premium cheese and paneer mix",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881901/cheese_paneer_mix_pxvhcr.png",
    isAvailable: true,
  },
  {
    name: "Shahi Paratha",
    price: 150,
    category: "Premium Paratha",
    description: "Royal style premium paratha",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881908/shahi_paratha_lcmgko.png",
    isAvailable: true,
  },
  {
    name: "Aloo Cheese Mix",
    price: 150,
    category: "Premium Paratha",
    description: "Premium potato and cheese",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881918/aloo_cheese_mix_w0obok.png",
    isAvailable: true,
  },
  {
    name: "Cocaine Paratha",
    price: 150,
    category: "Premium Paratha",
    description: "Special premium paratha",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881926/coconut_paratha_zzuark.png",
    isAvailable: true,
  },
  {
    name: "Aloo Onion Cheese Mix",
    price: 150,
    category: "Premium Paratha",
    description: "Premium potato, onion and cheese",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764881935/aloo_onion_cheese_mix_oa14bc.png",
    isAvailable: true,
  },

  // CHINESE STARTERS
  {
    name: "Veg Manchurian (Dry/Gravy)",
    price: 120,
    category: "Chinese Starters",
    description: "Vegetable manchurian dry or in gravy",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764917297/Gemini_Generated_Image_9ros709ros709ros_ozykh9.png",
    isAvailable: true,
  },
  {
    name: "Schezwan Manchurian (Dry/Gravy)",
    price: 120,
    category: "Chinese Starters",
    description: "Spicy schezwan manchurian",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764917379/Gemini_Generated_Image_vfsag4vfsag4vfsa_o4ryqi.png",
    isAvailable: true,
  },
  {
    name: "Gobi Manchurian (Dry/Gravy)",
    price: 120,
    category: "Chinese Starters",
    description: "Cauliflower manchurian",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764917638/Gemini_Generated_Image_jv7izzjv7izzjv7i_bnfti9.png",
    isAvailable: true,
  },
  {
    name: "Paneer Manchurian",
    price: 150,
    category: "Chinese Starters",
    description: "Paneer manchurian",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919253/paneer_manchurian_m8o2vy.png",
    isAvailable: true,
  },
  {
    name: "Paneer Chilli",
    price: 150,
    category: "Chinese Starters",
    description: "Paneer with green chilli",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919273/paneer_chilly_fwpvzs.png",
    isAvailable: true,
  },
  {
    name: "Paneer 65",
    price: 160,
    category: "Chinese Starters",
    description: "Paneer 65 style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919290/paneer_65_v71hrt.png",
    isAvailable: true,
  },
  {
    name: "Paneer Crispy",
    price: 180,
    category: "Chinese Starters",
    description: "Crispy paneer",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919323/paneer_crispy_remsbj.png",
    isAvailable: true,
  },
  {
    name: "Paneer Pepper Dry",
    price: 150,
    category: "Chinese Starters",
    description: "Paneer with pepper",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919334/paneer_pepper_dry_gdp8uf.png",
    isAvailable: true,
  },
  {
    name: "Paneer Schezwan Dry",
    price: 160,
    category: "Chinese Starters",
    description: "Spicy schezwan paneer",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919477/paneer_scezuan_dry_w4bjki.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Manchurian",
    price: 140,
    category: "Chinese Starters",
    description: "Mushroom manchurian",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919498/mushroom_manchurian_ipefem.png",
    isAvailable: true,
  },
  {
    name: "Mushroom 65",
    price: 150,
    category: "Chinese Starters",
    description: "Mushroom 65 style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919511/mushroom_65_qrvwfv.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Pepper Dry",
    price: 150,
    category: "Chinese Starters",
    description: "Mushroom with pepper",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919527/mushroom_pepper_dry_wqpqld.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Schezwan Dry",
    price: 160,
    category: "Chinese Starters",
    description: "Spicy mushroom",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919540/mushroom_schezuan_dry_mkqw7i.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Chilly",
    price: 150,
    category: "Chinese Starters",
    description: "Mushroom with chilli",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919561/mushroom_chilly_ey9a9b.png",
    isAvailable: true,
  },
  {
    name: "Baby Corn Manchurian",
    price: 130,
    category: "Chinese Starters",
    description: "Baby corn manchurian",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919594/baby_corn_manchurian_urhw26.png",
    isAvailable: true,
  },
  {
    name: "Baby Corn 65",
    price: 140,
    category: "Chinese Starters",
    description: "Baby corn 65 style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919602/baby_corn_65_xsawac.png",
    isAvailable: true,
  },
  {
    name: "Baby Corn Pepper Dry",
    price: 150,
    category: "Chinese Starters",
    description: "Baby corn with pepper",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919613/baby_corn_pepper_dry_d9hsir.png",
    isAvailable: true,
  },
  {
    name: "Baby Corn Chilly Dry",
    price: 150,
    category: "Chinese Starters",
    description: "Baby corn with chilli",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919621/baby_corn_chilly_dry_gqes4q.png",
    isAvailable: true,
  },

  // CHINESE SOUP
  {
    name: "Veg Manchow Soup",
    price: 80,
    category: "Chinese Soup",
    description: "Vegetable manchow soup",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919632/veg_manchow_soup_iknlfr.png",
    isAvailable: true,
  },
  {
    name: "Veg Clear Soup",
    price: 80,
    category: "Chinese Soup",
    description: "Clear vegetable soup",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919640/veg_clear_soup_wadzzr.png",
    isAvailable: true,
  },
  {
    name: "Veg Hot & Sour Soup",
    price: 80,
    category: "Chinese Soup",
    description: "Hot and sour vegetable soup",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919654/veg_hot_and_sour_soup_oivcag.png",
    isAvailable: true,
  },
  {
    name: "Tomato Soup",
    price: 80,
    category: "Chinese Soup",
    description: "Tomato soup",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919663/tomato_soup_zs8bz5.png",
    isAvailable: true,
  },
  {
    name: "Royal Soup",
    price: 90,
    category: "Chinese Soup",
    description: "Royal mixed soup",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919678/royal_soup_aa8rq2.png",
    isAvailable: true,
  },

  // CHINESE RICE
  {
    name: "Veg Fried Rice",
    price: 110,
    category: "Chinese Rice",
    description: "Vegetable fried rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919687/veg_fried_rice_ew4rs7.png",
    isAvailable: true,
  },
  {
    name: "Schezwan Fried Rice",
    price: 120,
    category: "Chinese Rice",
    description: "Spicy schezwan fried rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919704/schezuan_fried_ric_nbbcka.png",
    isAvailable: true,
  },
  {
    name: "Hong Kong Rice",
    price: 130,
    category: "Chinese Rice",
    description: "Hong kong style fried rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919712/hong_kong_rice_wdnahl.png",
    isAvailable: true,
  },
  {
    name: "Singapore Rice",
    price: 130,
    category: "Chinese Rice",
    description: "Singapore style rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919720/singapore_rice_wchhgd.png",
    isAvailable: true,
  },
  {
    name: "Manchurian Rice with Gravy",
    price: 160,
    category: "Chinese Rice",
    description: "Rice with manchurian gravy",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919776/manchurian_rice_with_gravy_u6zz5f.png",
    isAvailable: true,
  },
  {
    name: "Veg Triple Rice",
    price: 160,
    category: "Chinese Rice",
    description: "Triple vegetable rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919790/veg_triple_rice_fov4an.png",
    isAvailable: true,
  },
  {
    name: "Veg Chopper Rice",
    price: 140,
    category: "Chinese Rice",
    description: "Rice with chopped vegetables",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919800/veg_chopper_rice_h9fing.png",
    isAvailable: true,
  },
  {
    name: "Paneer Fried Rice",
    price: 160,
    category: "Chinese Rice",
    description: "Fried rice with paneer",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919813/paneer_fried_rice_tcvdea.png",
    isAvailable: true,
  },
  {
    name: "Paneer Chilli Rice",
    price: 160,
    category: "Chinese Rice",
    description: "Paneer chilli rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764919829/paneer_chilly_rice_jowaqx.png",
    isAvailable: true,
  },

  // TODAY THALI
  {
    name: "Roti Thali",
    price: 120,
    category: "Today Thali",
    description: "3 roti, dal-sabji-butter-salad-rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882848/roti_thali_sei5ia.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Thali",
    price: 140,
    category: "Today Thali",
    description: "3 roti, dal + jeera aloo + rice + raita + salad",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882877/verg_thali_tn02mj.jpg",
    isAvailable: true,
  },
  {
    name: "Rajma Thali",
    price: 150,
    category: "Today Thali",
    description: "3 roti, sabji + rajma, dal, rice, salad, raita",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882892/rajma_thali_n2tpyw.jpg",
    isAvailable: true,
  },
  {
    name: "Chole Masala Thali",
    price: 150,
    category: "Today Thali",
    description: "3 roti, sabji + masala chole + dal + raita + salad",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882899/chole_masala_thali_qukayf.jpg",
    isAvailable: true,
  },
  {
    name: "Paneer Thali",
    price: 160,
    category: "Today Thali",
    description: "3 roti, dal + jeera aloo + paneer + rice + salad",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882906/paneer_thali_uaujre.jpg",
    isAvailable: true,
  },

  // SPECIAL SABJI
  {
    name: "Dal Fry",
    price: 150,
    category: "Special Sabji",
    description: "Traditional lentil preparation",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882913/dal_fry_gkin2v.jpg",
    isAvailable: true,
  },
  {
    name: "Jeera Aloo",
    price: 140,
    category: "Special Sabji",
    description: "Potatoes with cumin",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882921/jeera_aloo_rfqwz9.jpg",
    isAvailable: true,
  },
  {
    name: "Dal Tarda",
    price: 160,
    category: "Special Sabji",
    description: "Dal with tempering",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882928/dal_tadka_n01oww.jpg",
    isAvailable: true,
  },
  {
    name: "Aloo Matar",
    price: 160,
    category: "Special Sabji",
    description: "Potato and peas",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764882935/aloo_matar_onn14d.jpg",
    isAvailable: true,
  },
  {
    name: "Shev Tomato",
    price: 150,
    category: "Special Sabji",
    description: "Vermicelli with tomato",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883002/shev_tomato_wexcoh.png",
    isAvailable: true,
  },
  {
    name: "Mix Veg",
    price: 160,
    category: "Special Sabji",
    description: "Mixed vegetables",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883111/mix_veg_sabji_ilbooe.jpg",
    isAvailable: true,
  },
  {
    name: "Besan Gatta",
    price: 160,
    category: "Special Sabji",
    description: "Gram flour dumplings in curry",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883123/besan_gatta_bmtyjn.jpg",
    isAvailable: true,
  },
  {
    name: "Paneer Bhurji",
    price: 200,
    category: "Special Sabji",
    description: "Crumbled paneer",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883131/paneer_bhurji_qeuyxy.jpg",
    isAvailable: true,
  },
  {
    name: "Paneer Pyaza",
    price: 180,
    category: "Special Sabji",
    description: "Paneer with onions",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883323/paneer_pyaza_qeafkp.png",
    isAvailable: true,
  },
  {
    name: "Paneer Butter Masala",
    price: 180,
    category: "Special Sabji",
    description: "Paneer in butter masala",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883332/paneer_butter_masala_xbatpo.png",
    isAvailable: true,
  },
  {
    name: "Paneer Masala",
    price: 170,
    category: "Special Sabji",
    description: "Paneer in spiced gravy",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883340/paneer_masala_nw8tum.png",
    isAvailable: true,
  },
  {
    name: "Palak Paneer",
    price: 160,
    category: "Special Sabji",
    description: "Spinach and paneer curry",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883347/palak_paneer_nmzihb.png",
    isAvailable: true,
  },
  {
    name: "Kadai Paneer",
    price: 180,
    category: "Special Sabji",
    description: "Paneer in kadai preparation",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883358/kadai_paneer_hqn71d.jpg",
    isAvailable: true,
  },
  {
    name: "Paneer Kolhapur",
    price: 180,
    category: "Special Sabji",
    description: "Paneer in Kolhapur style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883366/paneer_kolhapur_jljgko.jpg",
    isAvailable: true,
  },
  {
    name: "Paneer Handi",
    price: 180,
    category: "Special Sabji",
    description: "Paneer in handi style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883516/paneer_handi_zl50gc.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Masala",
    price: 180,
    category: "Special Sabji",
    description: "Mushroom in masala",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883526/mushroom_masala_oovqum.jpg",
    isAvailable: true,
  },
  {
    name: "Mushroom Ano Sala",
    price: 160,
    category: "Special Sabji",
    description: "Mushroom special preparation",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883545/mushroom_ano_sala_xidlgo.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Kadai",
    price: 170,
    category: "Special Sabji",
    description: "Mushroom kadai style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883553/mushroom_kadai_xq0lqy.png",
    isAvailable: true,
  },
  {
    name: "Mushroom Kolhapur",
    price: 170,
    category: "Special Sabji",
    description: "Mushroom in Kolhapur style",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883564/mushroom_kolhapur_bsnafl.png",
    isAvailable: true,
  },
  {
    name: "Matter Paneer",
    price: 170,
    category: "Special Sabji",
    description: "Paneer with peas",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883578/muttor_paneer_mdpfbt.jpg",
    isAvailable: true,
  },

  // CHINESE NOODLES
  {
    name: "Veg Noodles",
    price: 110,
    category: "Chinese Noodles",
    description: "Vegetable noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883598/veg_noodles_elpszk.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Schezwan Noodles",
    price: 120,
    category: "Chinese Noodles",
    description: "Spicy schezwan noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883651/veg_schexuan_nooodles_royavi.png",
    isAvailable: true,
  },
  {
    name: "Veg Manchurian Noodles",
    price: 160,
    category: "Chinese Noodles",
    description: "Noodles with manchurian",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883666/verg_manchurian_noodles_qj98ll.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Singapore Noodles",
    price: 130,
    category: "Chinese Noodles",
    description: "Singapore style noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883676/veg_singapore_noodles_u9icor.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Hong Kong Noodles",
    price: 130,
    category: "Chinese Noodles",
    description: "Hong kong style noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883684/veg_hong_kong_noodles_sytccg.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Triple Noodles",
    price: 160,
    category: "Chinese Noodles",
    description: "Triple mix noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883692/verg_triple_noodles_sphs1l.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Chopper Noodles",
    price: 170,
    category: "Chinese Noodles",
    description: "Chopped vegetable noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883702/verg_chopper_noodles_dzeq9y.jpg",
    isAvailable: true,
  },
  {
    name: "Veg Paneer Noodles",
    price: 150,
    category: "Chinese Noodles",
    description: "Noodles with paneer",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883835/veg_paneer_noodles_jhfeuy.png",
    isAvailable: true,
  },
  {
    name: "Paneer Chilly Noodles",
    price: 170,
    category: "Chinese Noodles",
    description: "Paneer chilli noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883845/paneer_chilly_noodles_eebp40.png",
    isAvailable: true,
  },
  {
    name: "Paneer Schezwan Noodles",
    price: 150,
    category: "Chinese Noodles",
    description: "Spicy paneer noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883856/paneer_schezuan_noodles_uziaz8.png",
    isAvailable: true,
  },

  // CHINESE COMBO
  {
    name: "Veg Combo",
    price: 250,
    category: "Chinese Combo",
    description: "Rice + Soup + Starter + Noodles",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764883866/veg_combo_snviwc.jpg",
    isAvailable: true,
  },
  {
    name: "Paneer Combo",
    price: 280,
    category: "Chinese Combo",
    description: "Rice + Soup + Starter + Gravy",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884113/paneer_combo_uas8ax.png",
    isAvailable: true,
  },

  // HOT AND COLD
  {
    name: "Masala Tea",
    price: 20,
    category: "Hot and Cold",
    description: "Traditional masala tea",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884123/masala_tea_up7kfz.jpg",
    isAvailable: true,
  },
  {
    name: "Masala Buttermilk",
    price: 30,
    category: "Hot and Cold",
    description: "Buttermilk with spices",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884132/masala_buttermilk_dmaqa3.jpg",
    isAvailable: true,
  },
  {
    name: "Sweet Lassi",
    price: 50,
    category: "Hot and Cold",
    description: "Sweet yogurt drink",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884141/sweet_lassi_e158aq.jpg",
    isAvailable: true,
  },
  {
    name: "Salt Lassi",
    price: 50,
    category: "Hot and Cold",
    description: "Salty yogurt drink",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884196/salt_lassi_vauu69.png",
    isAvailable: true,
  },

  // EXTRA
  {
    name: "Butter Roti",
    price: 15,
    category: "Extra",
    description: "Butter roti",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884216/buttur_roti_p03eml.jpg",
    isAvailable: true,
  },
  {
    name: "Curd",
    price: 10,
    category: "Extra",
    description: "Fresh curd",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764884224/curd_eqxpak.jpg",
    isAvailable: true,
  },
  {
    name: "Butter",
    price: 10,
    category: "Extra",
    description: "Butter",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764914372/Gemini_Generated_Image_uj6ab6uj6ab6uj6a_d8mjic.png",
    isAvailable: true,
  },
  {
    name: "Puri",
    price: 30,
    category: "Extra",
    description: "Puri (2 piece)",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764914631/Gemini_Generated_Image_c4gnh6c4gnh6c4gn_xzvlns.png",
    isAvailable: true,
  },
  {
    name: "Plain Rice",
    price: 50,
    category: "Extra",
    description: "Plain rice",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764915277/Gemini_Generated_Image_f2jaykf2jaykf2ja_xstzvo.png",
    isAvailable: true,
  },
  {
    name: "Churma",
    price: 50,
    category: "Extra",
    description: "Churma",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764914792/Gemini_Generated_Image_5pf02x5pf02x5pf0_mlptce.png",
    isAvailable: true,
  },
  {
    name: "Bati",
    price: 35,
    category: "Extra",
    description: "Bati",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764915195/Gemini_Generated_Image_f5pst1f5pst1f5ps_uo8cyo.png",
    isAvailable: true,
  },
  {
    name: "Extra Dal",
    price: 20,
    category: "Extra",
    description: "Extra lentils",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764917113/Gemini_Generated_Image_5f147v5f147v5f14_bpyjyg.png",
    isAvailable: true,
  },
  {
    name: "Extra Sabji",
    price: 20,
    category: "Extra",
    description: "Extra vegetables",
    imageUrl: "https://res.cloudinary.com/dhvs7hsuh/image/upload/v1764917121/Gemini_Generated_Image_b56snib56snib56s_bjfapf.png",
    isAvailable: true,
  },
];

const seedMenu = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      dbName: "MR_PARATHAS",
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log("✅ Connected to MongoDB");

    // Clear existing menu
    await Menu.deleteMany({});
    console.log("🗑️  Cleared existing menu items");

    // Insert new menu items
    const inserted = await Menu.insertMany(menuItems);
    console.log(`✅ Successfully seeded ${inserted.length} menu items`);

    // Display by category
    const categories = await Menu.distinct("category");
    console.log("\n📋 Menu Categories:");
    for (const cat of categories) {
      const count = await Menu.countDocuments({ category: cat });
      console.log(`  • ${cat}: ${count} items`);
    }

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding menu:", error.message);
    process.exit(1);
  }
};

seedMenu();